name: Auto merge depedndabot PRs
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-dependabot-prs:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Auto merge Dependabot PRs
        if: ${{steps.metadata.outputs.update-type != 'version-update:semver-major'}}
        uses: kachick/auto-merge-dependabot-prs-without-pat-after-workflows-passed@v1-beta
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
