name: Test & Deploy
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
      - 'elm.json'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/test_and_deploy.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jorelali/setup-elm@v3
        with:
          elm-version: 0.19.1
      - name: install npm dependencies
        run: npm install
      - name: Test
        run: ./node_modules/elm-test/bin/elm-test
      - run: elm make src/Main.elm --output=docs/main.js
      - name: git setting
        run: |
          git config --local user.email "kachick1@gmail.com"
          git config --local user.name "Kenichi Kamiya"
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d-%H%M-UTC"`
          BRANCH_NAME="deploy-$DATE"
          git checkout -b "$BRANCH_NAME"
          git add docs package-lock.json
          git commit -m 'Update with latest code'
          git push origin "$BRANCH_NAME":gh-pages --force
